// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        return android; // Fallback to android instead of throwing error
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhrCs4sKAYt7jr9OQMB1jt22CuOOsGi4E',
    appId: '1:52763236709:web:11febe982e11361937e98c',
    messagingSenderId: '52763236709',
    projectId: 'psfc-43b5a',
    authDomain: 'psfc-43b5a.firebaseapp.com',
    storageBucket: 'psfc-43b5a.firebasestorage.app',
    measurementId: 'G-VYSQ3VTHPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAod0xDUzLN0MVDZ1Er2OXA43xSk9MY0wk',
    appId: '1:52763236709:android:fd66e53d112fd1fe37e98c',
    messagingSenderId: '52763236709',
    projectId: 'psfc-43b5a',
    storageBucket: 'psfc-43b5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsUSN_pnLfNzBImaAxFwVACFU5GmuUNk0',
    appId: '1:52763236709:ios:b3db5d29b89e617a37e98c',
    messagingSenderId: '52763236709',
    projectId: 'psfc-43b5a',
    storageBucket: 'psfc-43b5a.firebasestorage.app',
    iosClientId: '52763236709-cfrgl63tvnublb11r48jnsvhd8c4ghkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.apnt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsUSN_pnLfNzBImaAxFwVACFU5GmuUNk0',
    appId: '1:52763236709:ios:b3db5d29b89e617a37e98c',
    messagingSenderId: '52763236709',
    projectId: 'psfc-43b5a',
    storageBucket: 'psfc-43b5a.firebasestorage.app',
    androidClientId: '52763236709-3ind557hlocvf43hdia57qc4lgsihf1k.apps.googleusercontent.com',
    iosClientId: '52763236709-cfrgl63tvnublb11r48jnsvhd8c4ghkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.apnt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhrCs4sKAYt7jr9OQMB1jt22CuOOsGi4E',
    appId: '1:52763236709:web:11febe982e11361937e98c',
    messagingSenderId: '52763236709',
    projectId: 'psfc-43b5a',
    authDomain: 'psfc-43b5a.firebaseapp.com',
    storageBucket: 'psfc-43b5a.firebasestorage.app',
    measurementId: 'G-VYSQ3VTHPV',
  );
}
